openapi: 3.1.0
info:
  title: CZERTAINLY Scheduler API
  description: REST API for managing Scheduler and its jobs in the platform
  contact:
    name: CZERTAINLY
    url: https://www.czertainly.com
    email: info@czertainly.com
  license:
    name: MIT License
    url: https://github.com/CZERTAINLY/CZERTAINLY/blob/develop/LICENSE.md
  version: 2.14.1-SNAPSHOT
  x-logo:
    url: images/czertainly_color_H.svg
externalDocs:
  description: CZERTAINLY Documentation
  url: https://docs.czertainly.com
servers:
- url: http://localhost:39449
  description: Generated server url
tags:
- name: Scheduled Jobs Management
  description: Scheduled Jobs Management API
paths:
  /v1/scheduler/jobs/{uuid}:
    get:
      tags:
      - Scheduled Jobs Management
      summary: Scheduled job detail
      operationId: getScheduledJobDetail
      parameters:
      - name: uuid
        in: path
        description: Scheduled job UUID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Scheduled job detail retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledJobDetailDto"
    put:
      tags:
      - Scheduled Jobs Management
      summary: Edit Scheduled job
      operationId: updateScheduledJob
      parameters:
      - name: uuid
        in: path
        description: Scheduled job UUID
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateScheduledJob"
        required: true
      responses:
        "200":
          description: Scheduled job updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledJobDetailDto"
    delete:
      tags:
      - Scheduled Jobs Management
      summary: Delete Scheduled job
      operationId: deleteScheduledJob
      parameters:
      - name: uuid
        in: path
        description: Scheduled job UUID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Scheduled job deleted
  /v1/scheduler/jobs/{uuid}/enable:
    patch:
      tags:
      - Scheduled Jobs Management
      summary: Enabling of Scheduled job
      operationId: enableScheduledJob
      parameters:
      - name: uuid
        in: path
        description: Scheduled job UUID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Scheduled job enabled
  /v1/scheduler/jobs/{uuid}/disable:
    patch:
      tags:
      - Scheduled Jobs Management
      summary: Disabling of Scheduled job
      operationId: disableScheduledJob
      parameters:
      - name: uuid
        in: path
        description: Scheduled job UUID
        required: true
        schema:
          type: string
      responses:
        "204":
          description: Scheduled job disabled
  /v1/scheduler/jobs:
    get:
      tags:
      - Scheduled Jobs Management
      summary: List of scheduled jobs
      operationId: listScheduledJobs
      parameters:
      - name: pagination
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/PaginationRequestDto"
      responses:
        "200":
          description: List of scheduled jobs fetched
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledJobsResponseDto"
  /v1/scheduler/jobs/{uuid}/history:
    get:
      tags:
      - Scheduled Jobs Management
      summary: Scheduled job history
      operationId: getScheduledJobHistory
      parameters:
      - name: pagination
        in: query
        required: true
        schema:
          $ref: "#/components/schemas/PaginationRequestDto"
      - name: uuid
        in: path
        description: Scheduled job UUID
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Scheduled job history retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScheduledJobHistoryResponseDto"
components:
  schemas:
    UpdateScheduledJob:
      type: object
      properties:
        cronExpression:
          type: string
          description: Cron expression for job schedule
    ScheduledJobDetailDto:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: UUID of the scheduled job
        jobName:
          type: string
          description: Name of the scheduled job
        jobType:
          type: string
          description: Type of scheduled job (job processor name)
        cronExpression:
          type: string
          description: CRON expression representing configuration of pattern how to
            run scheduled job
        enabled:
          type: boolean
          description: "Status of the scheduled job. True = Enabled, False = Disabled"
        oneTime:
          type: boolean
          description: Is scheduled job triggered only once
        system:
          type: boolean
          description: Is system scheduled job
        lastExecutionStatus:
          $ref: "#/components/schemas/SchedulerJobExecutionStatus"
          description: Execution status of last job triggered task
        userUuid:
          type: string
          format: uuid
        objectData:
          type: object
      required:
      - cronExpression
      - enabled
      - jobName
      - jobType
      - lastExecutionStatus
      - oneTime
      - system
      - uuid
    SchedulerJobExecutionStatus:
      type: string
      enum:
      - started
      - succeeded
      - failed
    PaginationRequestDto:
      type: object
      properties:
        itemsPerPage:
          type: integer
          format: int32
          default: "10"
          description: Number of entries per page
          maximum: 1000
        pageNumber:
          type: integer
          format: int32
          default: "1"
          description: Page number for the request
    ScheduledJobDto:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: UUID of the scheduled job
        jobName:
          type: string
          description: Name of the scheduled job
        jobType:
          type: string
          description: Type of scheduled job (job processor name)
        cronExpression:
          type: string
          description: CRON expression representing configuration of pattern how to
            run scheduled job
        enabled:
          type: boolean
          description: "Status of the scheduled job. True = Enabled, False = Disabled"
        oneTime:
          type: boolean
          description: Is scheduled job triggered only once
        system:
          type: boolean
          description: Is system scheduled job
        lastExecutionStatus:
          $ref: "#/components/schemas/SchedulerJobExecutionStatus"
          description: Execution status of last job triggered task
      required:
      - cronExpression
      - enabled
      - jobName
      - jobType
      - lastExecutionStatus
      - oneTime
      - system
      - uuid
    ScheduledJobsResponseDto:
      type: object
      properties:
        itemsPerPage:
          type: integer
          format: int32
          description: Number of entries per page
        pageNumber:
          type: integer
          format: int32
          description: Page number for the request
        totalPages:
          type: integer
          format: int32
          description: Number of pages available
        totalItems:
          type: integer
          format: int64
          description: Number of items available
        scheduledJobs:
          type: array
          description: Scheduled jobs
          items:
            $ref: "#/components/schemas/ScheduledJobDto"
      required:
      - itemsPerPage
      - pageNumber
      - scheduledJobs
      - totalItems
      - totalPages
    Resource:
      type: string
      enum:
      - NONE
      - dashboard
      - settings
      - auditLogs
      - credentials
      - connectors
      - attributes
      - jobs
      - notificationInstances
      - users
      - roles
      - acmeAccounts
      - acmeProfiles
      - scepProfiles
      - cmpProfiles
      - authorities
      - raProfiles
      - certificates
      - certificateRequests
      - groups
      - complianceProfiles
      - discoveries
      - entities
      - locations
      - tokenProfiles
      - tokens
      - keys
      - approvalProfiles
      - approvals
      - rules
      - actions
      - triggers
      - resources
      - resourceEvents
      - searchFilters
      - keyItems
      - platformEnums
      - notifications
      - conditions
      - executions
      - complianceRules
      - complianceGroups
      - customAttributes
      - globalMetadata
      - acmeOrders
      - acmeAuthorizations
      - acmeChallenges
      - cmpTransactions
      - endEntityProfiles
      - authenticationProviders
    ScheduledJobHistoryDto:
      type: object
      properties:
        jobUuid:
          type: string
          format: uuid
          description: Scheduled job UUID
        startTime:
          type: string
          format: date-time
          description: Start time of triggered task
        endTime:
          type: string
          format: date-time
          description: End time of triggered task
        status:
          $ref: "#/components/schemas/SchedulerJobExecutionStatus"
          description: Execution status of triggered task
        resultMessage:
          type: string
          description: Message explaining result status
        resultObjectType:
          $ref: "#/components/schemas/Resource"
          description: Result object type
        resultObjectIdentification:
          type: array
          description: Result object identification (UUID)
          items:
            type: string
      required:
      - startTime
      - status
    ScheduledJobHistoryResponseDto:
      type: object
      properties:
        itemsPerPage:
          type: integer
          format: int32
          description: Number of entries per page
        pageNumber:
          type: integer
          format: int32
          description: Page number for the request
        totalPages:
          type: integer
          format: int32
          description: Number of pages available
        totalItems:
          type: integer
          format: int64
          description: Number of items available
        scheduledJobHistory:
          type: array
          description: Scheduled job history
          items:
            $ref: "#/components/schemas/ScheduledJobHistoryDto"
      required:
      - itemsPerPage
      - pageNumber
      - scheduledJobHistory
      - totalItems
      - totalPages
